<template>
  <div>

    <!-- Title -->
    <div id="titleContainer">
      <h2><b>Portfolio</b></h2>
      <el-row>
        <router-link to="/createPortfolio">
          <el-button type="warning">Create New</el-button>
        </router-link>
      </el-row>
    </div>

    <!-- Portfolio Table -->
    <el-table
      :data="alert"
      :row-class-name="tableRowClassName"
      border
    >

      <!-- Username Column -->
      <el-table-column
        label="Currency"
        prop="EntryCurrencySym"
      >
      </el-table-column>
      <el-table-column
        label="Amount"
        prop="EntryValue"
      >
      </el-table-column>
      <el-table-column label="Action" 
        width="200px">
            <el-button type="warning">Edit</el-button>
            <el-button type="warning">Delete</el-button>
      </el-table-column>
    </el-table>
  </div>
</template>

<script>
export default {
  //=========================================// SAMPLE DATA //=======================================================//
  data() {
    return {
      alert: [
        {
          UserId: 1, //Primary Key: Generated by SQL statement to Database
          EntryCurrencySym: "USD",
          EntryValue: "111",
        },
      ],

      //b) TEST DATA: Current User Entity
      currentUser: {
        UserId: 1,
      },
    };
  },
  //=========================================// END OF SAMPLE DATA //=======================================================//
  methods: {
    handleView(index, row) {
      console.log(index, row);
    },
  },
  // b) DATA FROM DATABASE
  props: [],
};
</script>

<style scoped>
.el-table {
  width: 80%;
  margin-top: 50px;
  margin-right: 10%;
  margin-left: 10%;
}
.el-col {
  min-height: 1px;
}

#titleContainer {
  margin-top: 50px;
  height: 75px;
  text-align: left;
}

#titleContainer > h2 {
  font-size: 30pt;
  font-weight: bold;
  margin-left: 10%;
}
#titleContainer > .el-row {
  margin-left: 10%;
  height: 73px;
}
</style>